name: 'CI'

on:
  push:
    branches:
      - main
  pull_request: null

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 'Quality Control'

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Node and node_modules cache'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 'NPM install'
        run: npm install

      - name: 'Lint JS'
        run: 'npm run-script lint:js'

      - name: 'Lint CSS'
        run: 'npm run-script lint:css'